# Site settings
title: Smart Matter
email: hello@smartmatter.io
url: https://smartmatter.io
description: "Financial freedom without borders, it DOES matter!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Smart Matter

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SmartMatter_io
  - title: github
    url: https://github.com/smart-matter

# Build settings
markdown: kramdown
permalink: pretty
